# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Convertwithgeometry
                                 A QGIS plugin
 converts shapefile to raster with extent
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-27
        copyright            : (C) 2023 by Badal Singh
        email                : ce200004007@iiti.ac.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Convertwithgeometry class from file Convertwithgeometry.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .convert_shapefile import Convertwithgeometry
    return Convertwithgeometry(iface)
