# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Convertwithgeometry
                                 A QGIS plugin
 converts shapefile to raster with extent
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-06-27
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Badal Singh
        email                : ce200004007@iiti.ac.in
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject
from qgis.PyQt.QtCore import QObject
import processing, tempfile
from osgeo import gdal, gdalconst, ogr
import os
import subprocess

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .convert_shapefile_dialog import ConvertwithgeometryDialog
import os.path


class Convertwithgeometry:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # ...
        self.dlg = ConvertwithgeometryDialog()
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Convertwithgeometry_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Convert Shapefile to Raster')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Convertwithgeometry', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/convert_shapefile/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Shapefile to raster'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Convert Shapefile to Raster'),
                action)
            self.iface.removeToolBarIcon(action)
    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(self.dlg, "Select output file ", "", '*.tif')
        self.dlg.lineEdit.setText(filename)

    def get_layer_by_name(self, layer_name):
        """Get the layer object from the layer name."""
        layer = None
        layers = QgsProject.instance().mapLayersByName(layer_name)
        if layers:
            layer = layers[0]
        return layer

    def run(self, Shapefile_layer):
        """Run method that performs all the real work"""
        # ...

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ConvertwithgeometryDialog()
            self.dlg.pushButton.clicked.connect(self.select_output_file)

        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        # Populate the comboBox with names of all the loaded layers
        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_2.addItems([layer.name() for layer in layers])

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        
        # See if OK was pressed
        if result:
            # Retrieve the user-selected variables from the dialog
            tr_width = self.dlg.doubleSpinBox_3.value()
            tr_height = self.dlg.doubleSpinBox_2.value()
            init = 0
            burn_value = self.dlg.doubleSpinBox.value()
            Shapefile_layer = self.get_layer_by_name(self.dlg.comboBox.currentText())
            selected_layer = self.get_layer_by_name(self.dlg.comboBox_2.currentText())
            output_raster = self.dlg.lineEdit.text()

            # Get the extent of the selected layer
            extent = selected_layer.extent()
            te_xmin = extent.xMinimum()
            te_ymin = extent.yMinimum()
            te_xmax = extent.xMaximum()
            te_ymax = extent.yMaximum()

            # Call the function to convert the shapefile to raster using the user-selected variables
            self.convert_shapefile_to_raster(tr_width, tr_height, init, burn_value, selected_layer, output_raster, te_xmin, te_ymin, te_xmax, te_ymax, Shapefile_layer)

    def convert_shapefile_to_raster(
    self,
    tr_width,
    tr_height,
    init,
    burn_value,
    selected_layer,
    output_raster,
    te_xmin,
    te_ymin,
    te_xmax,
    te_ymax,
    Shapefile_layer
):
        """Convert the shapefile to raster using the provided variables."""
        # ...

        # Construct the GDAL command
        gdal_cmd = 'gdal_rasterize'
        args = [
            '-tr', str(tr_width), str(tr_height),
            '-burn', str(burn_value),
            '-te', str(te_xmin), str(te_ymin), str(te_xmax), str(te_ymax),
            '-init', str(init),
            Shapefile_layer.source(),
            output_raster # Pass the output_raster as a string
        ]
        full_cmd = [gdal_cmd] + args

        # Execute the GDAL command as a subprocess
        subprocess.call(full_cmd)